-- ============================================
-- DATA MIGRATION: JSON → Supabase
-- Run this AFTER supabase-schema.sql
-- ============================================

-- ============ STATS ============
INSERT INTO stats (name, value, icon, description, color, sort_order) VALUES
('Game Architecture', 85, 'data_object', 'Systems design & C# mastery in Unity.', '#10b981', 1),
('Product Vision', 88, 'lightbulb', 'Roadmap planning & UX strategy.', '#f59e0b', 2),
('Technical Discipline', 83, 'verified_user', 'Clean code & automated stability.', '#135bec', 3),
('Interactive Design', 90, 'draw', 'Crafting engaging game mechanics.', '#8b5cf6', 4);

-- ============ EXPERIENCES ============
INSERT INTO experiences (title, company, period, description, is_visible, sort_order) VALUES
('Test Engineer / QA Engineer', 'ERIKLABS', '07.10.2024 – 06.10.2025',
 ARRAY['QA consultancy at ATP for the Tradesoft project (mobile stock trading application).',
       'Designed and automated regression and functional tests using Cucumber (BDD) with Java.',
       'Performed API testing with RestAssured (automation), Karate (BDD), and Postman (manual).',
       'Integrated automated tests into the CI/CD pipeline.',
       'Contributed as a QA Engineer in a web project, supporting manual testing and quality assurance.'],
 true, 1),
('Associate Test Engineer', 'BLUECLOUD', '06.11.2023 – 27.09.2024',
 ARRAY['Performed manual and automation testing for the InXpress project.',
       'Developed automated BDD tests with Cucumber and Gherkin.',
       'Executed regression and smoke tests; tested new UAT features based on JIRA tickets.',
       'Automated CI/CD processes with Jenkins.',
       'Actively participated in daily stand-ups and sprint planning.'],
 true, 2),
('QA Automation Engineer Trainee', 'FEEDBACKFRUITS', '20.02.2023 – 18.08.2023',
 ARRAY['Specialized in frontend testing using Ember.js.',
       'Focused on UI acceptance tests to ensure quality and functionality.',
       'Built expertise in writing effective frontend tests.'],
 true, 3),
('QA Automation Engineer Intern', 'HUAWEI', '26.12.2022 – 17.02.2023',
 ARRAY['Worked in the QuickApp project''s Test and Automation team.',
       'Performed mobile tests on QuickApp IDE.',
       'Utilized DeviceFarmer with Docker for physical mobile device testing.'],
 true, 4),
('QA Automation Engineer Intern', 'IBTECH', '16.05.2022 – 16.11.2022',
 ARRAY['Set up test automation projects and analyzed test results.',
       'Gained hands-on experience with Selenium, Appium, and Robot Framework.'],
 true, 5);

-- ============ CERTIFICATIONS ============
INSERT INTO certifications (title, issuer, icon, rarity, url, sort_order) VALUES
('ISTQB® CTFL', 'ISTQB', 'verified_user', 'Legendary', 'https://app.diplomasafe.com/en-US/certificates/d76d532f338e53977cf2e5f8460dcb499b63ba8fc', 1),
('English - CEFR B2', 'Duolingo / CEFR', 'language', 'Epic', 'https://certs.duolingo.com/jhjl9gb0yssamblq', 2);

-- ============ REFERENCES ============
INSERT INTO references_list (name, role, text, avatar_url, linkedin, sort_order) VALUES
('Silas Hayri', 'Senior QA Automation Engineer at BlueCloud',
 'Emir takes full ownership of his work, maintains quality under pressure, and communicates with clarity, making him a true team player.',
 'https://media.licdn.com/dms/image/v2/D4D03AQF1wqYk4puQkA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1680395950289?e=1767830400&v=beta&t=XBkyJuZ-qO27gHn8ijKVbONAUid9V-ee1PwDjXiQSd8',
 'https://www.linkedin.com/in/silashayri', 1),
('Jordi Ruijs', 'Lead QA Engineer at FeedbackFruits',
 'Emir''s systematic approach to quality and his ability to think like both a developer and a tester are rare. He spots issues early and drives higher quality across the product.',
 'https://media.licdn.com/dms/image/v2/D4E03AQGZDvbbx9fW3Q/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1718268496655?e=1767830400&v=beta&t=ekT6x75i3cjwZE58SF4Khuc8WoFvZjh3o4Lr15j4Kco',
 'https://www.linkedin.com/in/jordiruijs/', 2),
('Ozan Can Altıok', 'Senior Software Engineer at BlueCloud',
 'Working with Emir means knowing your code will be tested thoroughly and your systems will be bulletproof.',
 'https://media.licdn.com/dms/image/v2/C5603AQHWg3AzQbnXQg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1567110034701?e=1767830400&v=beta&t=-sw2SCpdqs0VBIU6fM0CtXLaL-CzOWLbSUQwb7j9BF4',
 'https://www.linkedin.com/in/ozancanaltiok/', 3);

-- ============ GAME PROJECTS ============
INSERT INTO projects (slug, title, category, status, genre, engine, role, description, long_description, tags, image_url, platforms, mechanics, systems, roadmap, gallery, links, is_featured, sort_order) VALUES
('cardcheassy', 'CardCheassy', 'game', 'In Development', 'Strategy / Board', 'Unity',
 'Game Developer & Designer',
 'A unique game combining card-based strategy with tactical chess-like gameplay.',
 'CardCheassy is an experimental project merging classic chess logic with modern card-game mechanics. Players use cards to execute moves, position units, and ultimately aim to destroy the opponent''s King piece. It challenges players to think positionally while managing the flexibility of a card-driven hand, creating unique tactical scenarios in every match. The core loop focuses on decision-making, area control, and risk-reward balance.',
 ARRAY['Unity','C#','Turn-Based','Grid-System'],
 '/projects/games/CardCheassy.PNG',
 ARRAY['PC'],
 ARRAY['Unit positioning on a grid-based board','Card-driven movement (Action / Ability / Movement)','Card + Position synergy effects','Strict turn-based gameplay','Tactical area control','King-focused victory conditions','Risk-reward decision loop'],
 ARRAY['Core turn management system','Card hand and deck flow management','Board state evaluation logic','Rule-based win/loss detection','Planned basic AI opponent system'],
 ARRAY['Finalizing core game rules','Expansion of card variety and archetypes','Major UI/UX polish and feedback pass','Advanced AI behavior development','Comprehensive balance pass','Tutorial and onboarding integration'],
 ARRAY['/projects/games/CardCheassy-1.PNG','/projects/games/CardCheassy-2.PNG','/projects/games/CardCheassy-3.PNG'],
 '{}', true, 1),

('maggie', 'Maggie', 'game', 'In Development', '2D RPG Platformer', 'Unity',
 'Game Developer',
 'Stat-based 2D RPG platformer featuring sophisticated melee and ranged combat systems.',
 'Maggie is an action-RPG developed in a side-scrolling format. The project''s primary focus is building a stat-heavy, element-sensitive combat experience. Players engage with enemies using a variety of tools: parrying, countering, combo attacks, and elemental damage types. The system is designed to be highly responsive, featuring dynamic directionality and satisfying knockback effects.',
 ARRAY['Unity','C#','RPG','Combat-Systems'],
 '/projects/games/Maggie.PNG',
 ARRAY['PC'],
 ARRAY['Smooth 2D controller (Wall slide, Jump, Dash)','Melee and ranged integrated combat','Combo, Jump attack, and Wall jump attack variants','Counter / Parry system','Dynamic attack directionality','IDamageable interaction (destructibles)','Elemental damage mechanics (Fire, Ice, Lightning)'],
 ARRAY['Stat-based combat architecture','Health and regeneration systems','Attack speed and evasion logic','Physical damage + Critical hit calculations','Armor mitigation and penetration','Enemy AI State Machine','Dynamic UI (Health bars, Stat panels)'],
 ARRAY['Progression and leveling system','Interactable buff and world objects','Stat modifier systems (Temp/Permanent)','Skill tree system and UI','New enemy archetypes','Boss encounter design'],
 ARRAY['/projects/games/Maggie-1.PNG','/projects/games/Maggie-2.PNG','/projects/games/Maggie-3.PNG'],
 '{"github":"https://github.com/Eaylcn/Maggie"}', false, 2),

('spaceshooter2d', 'SpaceShooter2D', 'game', 'Prototype', 'Top-down Shooter', 'Unity',
 'Game Developer',
 'Top-down space shooter with free roaming, loot drops, and ship upgrade systems.',
 'SpaceShooter2D is a top-down prototype focused on exploration and combat within asteroid fields. The core gameplay loop involves navigating through space, fighting off enemy squadrons, and gathering loot to upgrade the player''s ship components such as engines, shields, and weapons.',
 ARRAY['Unity','C#','Top-Down','Loot-System'],
 '/projects/games/SpaceShooter.PNG',
 ARRAY['PC'],
 ARRAY['Top-down ship control and maneuvering','Free-roam space exploration','Combat against meteors and enemy craft','Multiple weapon types and shield mechanics','Loot collection and part upgrading'],
 ARRAY['Weapon, Engine, and Shield upgrade systems','Loot drop and inventory logic','Enemy wave spawn system','Zone-based progression structure'],
 ARRAY['Deep progression system (currently on hold)','New elite enemy types','Boss battle encounters','Economy and upgrade balancing','UI polish pass'],
 ARRAY['/projects/games/SpaceShooter-1.PNG','/projects/games/SpaceShooter-2.PNG','/projects/games/SpaceShooter-3.PNG'],
 '{}', false, 3),

('drone-shooter-3d', 'Drone Shooter 3D', 'game', 'Prototype', '3D Shooter', 'Unreal Engine',
 'Game Developer',
 'A 3D drone shooter prototype developed using Unreal Engine Blueprints.',
 'Drone Shooter 3D was created as a deep-dive into Unreal Engine''s Blueprint system. It focuses on aerial movement, aiming, and combat logic from a third-person perspective. The project serves as a technical study for movement feel and combat loops in a 3D arena.',
 ARRAY['UE4','Blueprint','Drone','TPS'],
 '/projects/games/DroneShooter.PNG',
 ARRAY['PC'],
 ARRAY['TPS drone controls (Hover / Forward / Strafe)','Aim and shoot combat loop','Enemy targeting systems','Arena-based test scenarios'],
 ARRAY['Blueprint-only movement system','Blueprint combat and projectile logic','Spawn management','Modular health system'],
 ARRAY['Logic reinforcement and optimization','Combat feedback and game feel improvements','Enemy variety trials','Camera and control polish'],
 ARRAY['/projects/games/DroneShooter-1.PNG','/projects/games/DroneShooter-2.PNG'],
 '{}', false, 4),

('split-fiction', 'Split Fiction Prototype', 'game', 'Experimental', 'Hybrid Perspective', 'Unreal Engine',
 'Game Developer',
 'An experimental project merging Side-scroller and TPS perspectives.',
 'Split Fiction Prototype explores the transition between 2D side-scrolling and 3D third-person perspectives within a single fluid experience. The project serves as R&D for camera transitions, movement mode switching, and experimental control schemes.',
 ARRAY['UE4','R&D','Hybrid-Perspective'],
 '/projects/games/SplitFictionPrototype.PNG',
 ARRAY['PC'],
 ARRAY['Side-scroller movement logic','TPS movement logic','Trigger-based camera perspective switching','Experimental hybrid control schemes'],
 ARRAY['Perspective transition system','Movement mode switching logic','Blueprint-based rapid prototyping','Technical validation test scenes'],
 ARRAY['Stabilization of Perspective ↔ Movement transitions','General movement feel polish','Smoothing of camera lerping','First playable prototype validation'],
 ARRAY['/projects/games/SplitFictionPrototype-1.PNG','/projects/games/SplitFictionPrototype-2.PNG','/projects/games/SplitFictionPrototype-3.PNG','/projects/games/SplitFictionPrototype-4.PNG'],
 '{}', false, 5);

-- ============ MOBILE PROJECTS ============
INSERT INTO projects (slug, title, category, status, role, description, long_description, tags, image_url, platforms, tech_stack, features, systems, roadmap, screenshots, links, is_featured, sort_order) VALUES
('tuty', 'Tuty', 'mobile', 'In Development',
 'Solo Developer / Full-Stack Mobile Architect',
 'Your beauty collection, intelligently organized. A smart inventory system for makeup and skincare.',
 'Tuty was born from the need to manage makeup and skincare collections for users who feel they are losing control. It''s an intelligent mobile application designed to solve the chaos of duplicate purchases and missed expiration dates. Tuty provides real-time awareness: what you have, what is running out, and what needs to be replaced. It eventually learns user habits to provide more accurate predictions and suggestions, with AI Assistant Lily at the heart of its future vision.',
 ARRAY['Flutter','Firebase','Dart','Beauty-Tech'],
 '/projects/mobile/Tuty.PNG',
 ARRAY['iOS','Android'],
 ARRAY['Flutter','Dart','Firebase Auth','Cloud Firestore','Riverpod','OpenBeautyFacts API'],
 ARRAY['Barcode Scanning for automatic product detection','Smart Expiration Date (SKT) Alerts','Color & Shade Code Tracking','Stash / Wishlist Separation','Daily Missions & Gamified Engagement','AI Assistant Lily (Premium / In Dev)','Dark / Light Mode & Multi-language Support'],
 ARRAY['Offline-first data architecture','Adaptive product lifespan calculator','Usage-based prediction system (Premium)','Clean Architecture (Feature-based modular structure)','Premium feature gating'],
 ARRAY['Lily AI Integration','Push Notification System','Cloud Storage for Product Images','Collection Sharing & Price Comparison','Purchase Reminders & Widget Support'],
 ARRAY['/projects/mobile/Tuty-1.PNG','/projects/mobile/Tuty-2.PNG','/projects/mobile/Tuty-3.PNG','/projects/mobile/Tuty-4.PNG'],
 '{}', true, 6),

('quantum-agent', 'Quantum Agent', 'mobile', 'In Development',
 'Game Designer & Developer',
 'A mobile swipe game about time travel where every decision alters the timeline.',
 'Quantum Agent is a narrative-driven decision game designed for mobile. Players swipe left or right on event cards to manage agents and manipulate time. Every choice has lasting effects on agent stats and the stability of the timeline. The game blends branching storytelling with risk management and resource control.',
 ARRAY['Unity','C#','Mobile','Narrative'],
 '/projects/mobile/QuantumAgent.PNG',
 ARRAY['iOS','Android'],
 ARRAY['Unity','C#','Narrative Trees','Mobile Input'],
 ARRAY['Swipe-based decision making','Branching narrative architecture','Agent and Resource management','Timeline impact tracking','Event-based card pool','Risk-based mission failure scenarios'],
 ARRAY['Mobile swipe input manager','Recursive decision tree system','Agent stat management','Dynamic timeline stability calculation','Event pool and probability scaling'],
 ARRAY['Completion of MVP decision sets','Expansion of agent status effects','Timeline stability visualization','Unlockable event cards and progression','UI/UX feedback pass','Atmospheric audio integration'],
 ARRAY['/projects/mobile/QuantumAgent-1.PNG','/projects/mobile/QuantumAgent-2.PNG'],
 '{}', false, 7),

('zoo-merge', 'Merge Kingdom', 'mobile', 'MVP Development',
 'Game Developer & Systems Architect',
 'A casual Merge-2 mobile game blending village management, strategic unit crafting, and auto-battles against mythical creatures.',
 E'Merge Kingdom (formerly known as Zoo Merge) is an expansive casual mobile game that evolves the traditional Merge-2 formula by integrating village building and automated RPG combat. Players act as the ruler of a kingdom, managing a 7x9 grid where they construct facilities, produce resources (gold, food, materials), and train a diverse army of humans, elves, dwarves, and orcs.\n\nThe core loop revolves around merging base items to upgrade them, which are then used in the Portal to craft fully armed soldiers. These units are deployed in tactical auto-battles against a progression of enemies and bosses. Designed as a showcase of Advanced Agentic Coding, the game is built entirely in Unity with C# through LLM pair-programming. It features a highly modular architecture using a custom ScriptableObject framework, an extensive Object Pooling system managing a dual-board 126-slot grid, and robust managers handling procedurally generated orders, complex item synergies, and continuous backend production calculations.',
 ARRAY['Unity','C#','Merge-2','Agentic Coding','RPG'],
 '/projects/mobile/merge2Game-1.PNG',
 ARRAY['iOS','Android'],
 ARRAY['Unity','C#','Generative AI','Mobile UI/UX','ScriptableObjects','Object Pooling','DOTween','JSON Serialization'],
 ARRAY['Drag & drop Merge-2 mechanics with smart hint system','Dual-board system: Main Village for production and Portal for combat','Village management with 7 distinct building types and auto-generators','Deep crafting system: Base Soldier + Equipment = Combat-ready unit','Auto-battle combat system with stage-based progression and Boss fights','Intricate synergy mechanics based on unit race (Elf, Dwarf, etc.) and class','Rune and healing potion systems via stackable modifier items','Dynamic merchant, stash management, and procedural order systems'],
 ARRAY['Extensive Object Pooling system handling 126 active slots across two boards','Custom ScriptableObject-driven architecture for items, units, rules and synergies','Clean DRY implementation with abstract BaseGridManager for dual boards','Robust Save/Load system utilizing JSON and PlayerPrefs for board state','ProductionManager to simulate logic for active and passive boards','UI Culling and rendering subsystem for background grid optimization'],
 ARRAY['Phase 1: Village & Production System (Buildings, Generators, Economics)','Phase 2: Portal Combat & Rune System (Auto-battles, Loot, Synergies)','Phase 3: Balance & Game Depth (Scaling difficulty, Advanced Synergies)','Phase 4: Endgame Metagame (Hero System, Gacha Mechanics, Hero Skills)','Phase 5: PvP & Live Ops Content'],
 ARRAY['/projects/mobile/merge2Game-1.PNG','/projects/mobile/merge2Game-2.PNG','/projects/mobile/merge2Game-3.PNG','/projects/mobile/merge2Game-4.PNG','/projects/mobile/merge2Game-5.PNG'],
 '{}', false, 8);

-- ============ WEB PROJECTS ============
INSERT INTO projects (slug, title, category, status, role, description, long_description, tags, image_url, platforms, tech_stack, features, screenshots, links, is_featured, sort_order) VALUES
('khaeltheron', 'Khaeltheron', 'web', 'Live',
 'Creative Developer & Systems Designer',
 'A dark fantasy lore-first digital archive and worldbuilding showcase.',
 'Khaeltheron was designed as a story-driven web experience set in a dark fantasy atmosphere. The goal was to create a digital showcase for an expanding universe, acting more as a digital grimoire than a standard website. I architected the concept, narrative structure, visual flow, and end-to-end user experience, focusing on immersive lore and atmospheric UI.',
 ARRAY['HTML','CSS','Lore-Building','Narrative-UX'],
 '/projects/web/KaelTheron.PNG',
 ARRAY['Web'],
 ARRAY['HTML','CSS','JavaScript','Custom Layouts','Typography Systems'],
 ARRAY['Universe-centric page architecture','Atmosferic UI (Dark Fantasy Tone)','Lore-based content hierarchy','Exploration-driven user discovery','Custom grimoire-style visual components'],
 ARRAY['/projects/web/KaelTheron-1.PNG','/projects/web/KaelTheron-2.PNG','/projects/web/KaelTheron-3.PNG'],
 '{"live":"https://khaeltheron.vercel.app"}', false, 9),

('qa-forge-archive', 'The Grand Archive', 'web', 'Live',
 'Full-Stack Architect & UI Designer',
 'An RPG-themed professional portfolio integrated with Gemini AI for a sentient-style experience.',
 'The Grand Archive is a high-fidelity professional showcase designed to bridge the gap between technical engineering and creative game design. It features a custom-inspired UI system, interactive skill displays, and a sentient AI companion, the Data Drake, powered by the Gemini API. The project demonstrates advanced React patterns, complex Tailwind styling, and seamless AI integration.',
 ARRAY['React','Gemini-API','Tailwind','TypeScript'],
 '/projects/web/thegrandarchive.PNG',
 ARRAY['Web','AI'],
 ARRAY['React 19','TypeScript','Tailwind CSS','Gemini API','React Router'],
 ARRAY['Sentient AI Companion (Data Drake)','Stat & Inventory System','Narrative architecture','Responsive High-Fidelity Dashboard UI','Dynamic project archiving'],
 ARRAY['/projects/web/thegrandarchive.PNG','/projects/web/thegrandarchive-1.PNG','/projects/web/thegrandarchive-2PNG.PNG'],
 '{"github":"https://github.com/Eaylcn/PortfolioWebsite","live":"https://eaylcn.com"}', true, 10),

('ponyfart', 'PonyFart', 'web', 'Live',
 'Solo Developer (Vibecoding & Logic)',
 'A playful experimental web game developed with a high-creativity vibe-coding approach.',
 'PonyFart is a fun-oriented web game developed using a vibecoding approach. The project prioritizes rapid production, creative flow, and a humorous experience over rigid technical structures. It features browser-based gameplay with a focus on simple yet fluid input mechanics.',
 ARRAY['JavaScript','WebGame','Vibecoding','GitHub-Pages'],
 '/projects/web/PonyFart.PNG',
 ARRAY['Web'],
 ARRAY['HTML','CSS','JavaScript','GitHub Pages'],
 ARRAY['Browser-based interactive gameplay','Fluid and responsive input system','Lightweight architecture for instant loading','Humor-driven UX and visual style','Continuous deployment via GitHub'],
 ARRAY['/projects/web/PonyFart-1.PNG','/projects/web/PonyFart-2.PNG','/projects/web/PonyFart-3.PNG'],
 '{"live":"https://eaylcn.github.io/PonyFart/","github":"https://github.com/Eaylcn/PonyFart"}', false, 11);
